# Generated by Django 5.0.1 on 2024-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Desc_diag", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Derniere_modif", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom_M", models.CharField(max_length=50)),
                ("Prenom_M", models.CharField(max_length=50)),
                (
                    "Telephone_M",
                    models.CharField(
                        help_text="Entrez un numero de telephone valable svp",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom_Medic", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Designation", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom_P", models.CharField(max_length=50)),
                ("Prenom_P", models.CharField(max_length=50)),
                ("DateNaissance", models.DateField()),
                (
                    "Telephone_P",
                    models.CharField(
                        help_text="Entrez un numero de telephone valable svp",
                        max_length=10,
                    ),
                ),
                ("Adresse_P", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_rdv", models.DateTimeField()),
            ],
        ),
    ]
