# Generated by Django 5.0.1 on 2024-01-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnostic",
            name="id",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="id",
        ),
        migrations.RemoveField(
            model_name="medecin",
            name="id",
        ),
        migrations.RemoveField(
            model_name="medicament",
            name="id",
        ),
        migrations.RemoveField(
            model_name="ordonnance",
            name="id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="id",
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="Num_Diag",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="Num_ordonnance",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.ordonnance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="Num_rendezvous",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.rendezvous",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dossier",
            name="Num_D",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dossier",
            name="Num_Patient",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medecin",
            name="Num_M",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medecin",
            name="Num_rendezvous",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.rendezvous",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicament",
            name="Code_Medic",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordonnance",
            name="Medicaments",
            field=models.ManyToManyField(to="app1.medicament"),
        ),
        migrations.AddField(
            model_name="ordonnance",
            name="Num_diagnostic",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.diagnostic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordonnance",
            name="Num_ord",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="Num_P",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="Num_rendezvous",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.rendezvous",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="num_dossier",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.dossier",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="Num_Diagnostic",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.diagnostic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="Num_rdv",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
