# Generated by Django 5.0.1 on 2024-01-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_diagnostic_num_diag_alter_dossier_num_d_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="salle",
            fields=[
                (
                    "Num_salle",
                    models.AutoField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "type_salle",
                    models.CharField(
                        choices=[
                            ("operation", "salle d'opération"),
                            ("consultation", "salle de consultation"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
