# Generated by Django 5.0.1 on 2024-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_remove_diagnostic_num_ordonnance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Genre",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Feminin")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
    ]
