# Generated by Django 5.0.1 on 2024-01-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_patient_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="specialite",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Neurologist", "Neurologist"),
                    ("Urologist", "Urologist"),
                    ("Rheumatologist", "Rheumatologist"),
                    ("Otolaryngologist", "Otolaryngologist"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rendezvous",
            name="Num_Patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.patient"
            ),
        ),
    ]
