# Generated by Django 5.0.1 on 2024-01-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_salle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medecin",
            name="Num_rendezvous",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Num_rendezvous",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="num_dossier",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="Num_Diagnostic",
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="Num_Medecin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.medecin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="Num_Patient",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="Salle",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app1.salle"
            ),
            preserve_default=False,
        ),
    ]
