<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-27 11:24
=======
# Generated by Django 5.0.1 on 2024-01-27 11:15
>>>>>>> bfec6ff (salut)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('app1', '0003_patient_genre'),
=======
    dependencies = [
        ("app1", "0003_patient_genre"),
>>>>>>> bfec6ff (salut)
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='rendezvous',
            name='Num_Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient'),
=======
            model_name="rendezvous",
            name="Num_Patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.patient"
            ),
>>>>>>> bfec6ff (salut)
        ),
    ]
