# Generated by Django 5.0.1 on 2024-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_rendezvous_num_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="specialite",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Neurologist", "Neurologist"),
                    ("Urologist", "Urologist"),
                    ("Rheumatologist", "Rheumatologist"),
                    ("Otolaryngologist", "Otolaryngologist"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
