# Generated by Django 5.0.1 on 2024-01-26 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_remove_medecin_num_rendezvous_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rendezvous",
            old_name="Salle",
            new_name="salle",
        ),
    ]
