# Generated by Django 5.0.1 on 2024-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_rename_salle_rendezvous_salle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnostic",
            name="Num_ordonnance",
        ),
        migrations.AlterField(
            model_name="diagnostic",
            name="Num_Diag",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="Num_D",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medecin",
            name="Num_M",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medicament",
            name="Code_Medic",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ordonnance",
            name="Num_ord",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Num_P",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rendezvous",
            name="Num_rdv",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salle",
            name="Num_salle",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
